# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Skiff < Formula
  desc "Skiff — opinionated mouse-first terminal code editor."
  homepage "https://github.com/johnlam90/skiff"
  version "0.2.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/johnlam90/skiff/releases/download/v0.2.6/skiff_0.2.6_darwin_amd64.tar.gz"
      sha256 "90e2a40eedc092fc3d130eb08027ca84d182efa446cac36057b3efc1c9a7d64f"

      define_method(:install) do
        bin.install "skiff"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/johnlam90/skiff/releases/download/v0.2.6/skiff_0.2.6_darwin_arm64.tar.gz"
      sha256 "0f00c32c25c5fa9a6d43f9133f769974b0d406ef7e40af9c536ea3e1e9947868"

      define_method(:install) do
        bin.install "skiff"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/johnlam90/skiff/releases/download/v0.2.6/skiff_0.2.6_linux_amd64.tar.gz"
      sha256 "56cb00625683242289f764341788371b57e57caaaa768dee5cd1b5e9cd6b990c"
      define_method(:install) do
        bin.install "skiff"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/johnlam90/skiff/releases/download/v0.2.6/skiff_0.2.6_linux_arm64.tar.gz"
      sha256 "1ce67db2614c46c555428d4563fc8e5015a7345a320e6c0822f718815a767dcc"
      define_method(:install) do
        bin.install "skiff"
      end
    end
  end

  test do
    assert_match "skiff #{version}", shell_output("#{bin}/skiff --version")
    assert_match "action menu", shell_output("#{bin}/skiff --help")
  end
end
