# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Skiff < Formula
  desc "Skiff — opinionated mouse-first terminal code editor."
  homepage "https://github.com/johnlam90/skiff"
  version "0.1.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/johnlam90/skiff/releases/download/v0.1.5/skiff_0.1.5_darwin_amd64.tar.gz"
      sha256 "777e80472168a726bd7be3f3f48b9ac3a982a4ac2f37167da24def2b00534a7f"

      define_method(:install) do
        bin.install "skiff"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/johnlam90/skiff/releases/download/v0.1.5/skiff_0.1.5_darwin_arm64.tar.gz"
      sha256 "a8e343fe0ff361cc03e01011d06d2ce021e872cfc3d92144a6ae183e09d738dc"

      define_method(:install) do
        bin.install "skiff"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/johnlam90/skiff/releases/download/v0.1.5/skiff_0.1.5_linux_amd64.tar.gz"
      sha256 "20141fd80d807c83c109a2a3f8e31f2ba0c863fc78b2e86f187f420982b05e84"
      define_method(:install) do
        bin.install "skiff"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/johnlam90/skiff/releases/download/v0.1.5/skiff_0.1.5_linux_arm64.tar.gz"
      sha256 "22730a5254ef4d4a8bfb70a630b15be3ff5274fbe5fd4a4ae565a2cf70d8d8ce"
      define_method(:install) do
        bin.install "skiff"
      end
    end
  end

  test do
    assert_path_exists bin/"skiff"
  end
end
