# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Skiff < Formula
  desc "Skiff — opinionated mouse-first terminal code editor."
  homepage "https://github.com/johnlam90/skiff"
  version "0.2.23"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/johnlam90/skiff/releases/download/v0.2.23/skiff_0.2.23_darwin_amd64.tar.gz"
      sha256 "ba192c9ab471848104b7fc833a3dd1f755111a1d36d30aaf9afb8e7dc0073391"

      define_method(:install) do
        bin.install "skiff"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/johnlam90/skiff/releases/download/v0.2.23/skiff_0.2.23_darwin_arm64.tar.gz"
      sha256 "aa2a4127576bf969683b15becc2c9b35ba7dd6fa07155aa9c012b58a9b29a33b"

      define_method(:install) do
        bin.install "skiff"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/johnlam90/skiff/releases/download/v0.2.23/skiff_0.2.23_linux_amd64.tar.gz"
      sha256 "05284d2616fdc5d8cdd026122ca4613f78a6522ac955ac5a2c2adf7d3762ff6d"
      define_method(:install) do
        bin.install "skiff"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/johnlam90/skiff/releases/download/v0.2.23/skiff_0.2.23_linux_arm64.tar.gz"
      sha256 "bc007d0a58d1e60d0e903e247f8e418cdc872c790c5c5ba0f6893e8773a21e16"
      define_method(:install) do
        bin.install "skiff"
      end
    end
  end

  test do
    assert_match "skiff #{version}", shell_output("#{bin}/skiff --version")
    assert_match "action menu", shell_output("#{bin}/skiff --help")
  end
end
